# https://docs.strapi.io/dev-docs/plugins/users-permissions#authentication
@base=http://localhost:1337
# @base=https://strapi.saber2pr.top

### register

POST {{base}}/api/auth/local/register
Content-Type: application/json

{  "username":"saber2pr",  "password":"123456", "email": "saber2pr@gmail.com" }

### login

POST {{base}}/api/auth/local
Content-Type: application/json

{  "identifier":"saber2pr",  "password":"0729abcd." }

### get user info

GET {{base}}/api/users/me
Content-Type: application/json
Authorization: Bearer 

### send reset password code email

POST {{base}}/api/auth/forgot-password
Content-Type: application/json

{
  "email": "saber2pr@gmail.com"
}

### reset password

POST {{base}}/api/auth/reset-password
Content-Type: application/json

{
  "code": "",
  "password": "1234",
  "passwordConfirmation": "1234"
}

### get current user product paylink

GET https://strapi.saber2pr.top/strapi-paypal/getProduct/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzA5NTM1NzI0LCJleHAiOjE3MTIxMjc3MjR9.MLOSHFHm4D9vrDP_ovQr6i6D1K2xRcbBWylCj8QqFhg

### get pay status

GET https://strapi.saber2pr.top/strapi-paypal/getPaypalCheckout/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzA5NTM1NzI0LCJleHAiOjE3MTIxMjc3MjR9.MLOSHFHm4D9vrDP_ovQr6i6D1K2xRcbBWylCj8QqFhg

### pid

GET {{base}}/api/config
